class Texts {
  static const es = {
    "posts": "Publicaciones",
    "noPosts": "No hay publicaciones aún.",
    "edit": "Editar",
    "delete": "Eliminar",
    "createdAt": "Fecha",
    "author": "Autor",
    "createPost": "Crear publicación",
    "backToTop": "Volver arriba",
    "editProfile": "Editar Perfil",
    "name": "Nombre",
    "email": "Correo electrónico",
    "newPassword": "Nueva contraseña (opcional)",
    "logout": "Cerrar sesión",
    "uploading": "Subiendo...",
    "saveImage": "Guardar imagen",
    "saveChanges": "Guardar cambios",
    "changeLanguage": "Cambiar idioma",
    "emailVerificationSent": "Verificación de correo enviada",
    "profileUpdated": "Perfil actualizado",
    "error": "Error",
    "myFriends": "Mis Amigos",
    "noFriends": "No tienes amigos todavía",
    "otherPlayers": "Otros Jugadores",
    "player": "Jugador",
    "requestSent": "Solicitud enviada correctamente",
    "add": "Agregar",
    "achievements": "Logros",
    "friends": "Amigos",
    "home": "Inicio",
    "community": "Comunidad",
    "settings": "Configuración",
    "of": "de",
    "addAchievement": "Agregar nuevo logro",
    "achievementTitle": "Título del logro",
    "description": "Descripción",
    "cancel": "Cancelar",
    "save": "Guardar",
    "editAchievement": "Editar Logro",
    "friendRequests": "Solicitudes de Amistad",
    "noPendingRequests": "No tienes solicitudes pendientes.",
    "invalidRequest": "Solicitud inválida",
    "invalidUserId": "El ID del usuario no es válido.",
    "fillAllFields": "Completa todos los campos",
    "postCreated": "Publicación creada",
    "postError": "Error al publicar:",
    "title": "Título",
    "content": "Contenido",
    "selectImage": "Seleccionar imagen",
    "publish": "Publicar",
    "editPost": "Editar publicación",
  };

  static const en = {
    "posts": "Posts",
    "noPosts": "No posts yet.",
    "edit": "Edit",
    "delete": "Delete",
    "createdAt": "Date",
    "author": "Author",
    "createPost": "Create Post",
    "backToTop": "Back to Top",
    "editProfile": "Edit Profile",
    "name": "Name",
    "email": "Email",
    "newPassword": "New password (optional)",
    "logout": "Logout",
    "uploading": "Uploading...",
    "saveImage": "Save Image",
    "saveChanges": "Save Changes",
    "changeLanguage": "Change language",
    "emailVerificationSent": "Email verification sent",
    "profileUpdated": "Profile updated",
    "error": "Error",
    "myFriends": "My Friends",
    "noFriends": "You have no friends yet",
    "otherPlayers": "Other Players",
    "player": "Player",
    "requestSent": "Request sent correctly",
    "add": "Add",
    "achievements": "Achievements",
    "friends": "Friends",
    "home": "Home",
    "community": "Community",
    "settings": "Settings",
    "of": "of",
    "addAchievement": "Add new achievement",
    "achievementTitle": "Achievement Title",
    "description": "Description",
    "cancel": "Cancel",
    "save": "Save",
    "editAchievement": "Edit Achievement",
    "friendRequests": "Friend Requests",
    "noPendingRequests": "You have no pending requests.",
    "invalidRequest": "Invalid request",
    "invalidUserId": "The user ID is not valid.",
    "fillAllFields": "Please complete all fields",
    "postCreated": "Post created",
    "postError": "Error posting:",
    "title": "Title",
    "content": "Content",
    "selectImage": "Select Image",
    "publish": "Publish",
    "editPost": "Edit Post",
    "password": "Password",
    "login": "Login",
    "register": "Register",
  };

  static String t(String key, bool isEnglish) {
    return isEnglish ? en[key] ?? key : es[key] ?? key;
  }
}
